[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_echo = yes
monitor_filters =
  esp32_exception_decoder
  send_on_enter
lib_deps =
  bblanchon/ArduinoJson@7.3.1
build_flags =
  -DCORE_DEBUG_LEVEL=0
extra_scripts =
  pre:scripts/git_revision.py
